name: behaviormind
description: A Flutter-based app that collects sensor data from devices and wearables to predict human behavior patterns and provide wellness insights.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  fl_chart: ^0.65.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  http: ^1.1.0
  sensors_plus: ^4.0.2
  health: ^8.0.0
  permission_handler: ^11.0.1
  local_auth: ^2.1.7
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^16.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/